version: '3.9'

volumes:
    prometheus_data:
    
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"

  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379

  blackbox_exporter:
    image: prom/blackbox-exporter:v0.19.0
    volumes:
    - ./configs/blackbox_exporter/config.yml:/etc/blackbox_exporter/config.yml
    restart: unless-stopped

  prometheus:
    image: 'prom/prometheus:v2.28.0'
    ports:
        - 9090:9090
    volumes:
        - './configs/prometheus/targets:/etc/prometheus/targets'
        - './configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
        - 'prometheus_data:/prometheus'
    command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--storage.tsdb.retention.time=70d'
        - '--log.level=debug'
        - '--web.enable-lifecycle'
    restart: unless-stopped